const foods = [
  // === PIZZA ===
  ['Cheese Pizza', 'meal', 285, '1 slice'],
  ['Pepperoni Pizza', 'meal', 310, '1 slice'],
  ['Margherita Pizza', 'meal', 270, '1 slice'],
  ['Hawaiian Pizza', 'meal', 290, '1 slice'],
  ['BBQ Chicken Pizza', 'meal', 320, '1 slice'],
  ['Meat Lovers Pizza', 'meal', 350, '1 slice'],
  ['Veggie Pizza', 'meal', 260, '1 slice'],
  ['Supreme Pizza', 'meal', 340, '1 slice'],
  ['Buffalo Chicken Pizza', 'meal', 330, '1 slice'],
  ['White Pizza', 'meal', 300, '1 slice'],
  ['Mushroom Pizza', 'meal', 275, '1 slice'],
  ['Sausage Pizza', 'meal', 325, '1 slice'],
  ['Four Cheese Pizza', 'meal', 310, '1 slice'],
  ['Thin Crust Cheese Pizza', 'meal', 220, '1 slice'],
  ['Deep Dish Cheese Pizza', 'meal', 380, '1 slice'],
  ['Stuffed Crust Pizza', 'meal', 360, '1 slice'],
  ['Frozen Pizza (whole)', 'meal', 1200, '1 pizza'],

  // === BURGERS ===
  ['Cheeseburger', 'meal', 350, '1 burger'],
  ['Hamburger', 'meal', 300, '1 burger'],
  ['Double Cheeseburger', 'meal', 550, '1 burger'],
  ['Bacon Cheeseburger', 'meal', 430, '1 burger'],
  ['Turkey Burger', 'meal', 280, '1 burger'],
  ['Veggie Burger', 'meal', 260, '1 burger'],
  ['Black Bean Burger', 'meal', 270, '1 burger'],
  ['Mushroom Swiss Burger', 'meal', 420, '1 burger'],
  ['BBQ Bacon Burger', 'meal', 480, '1 burger'],
  ['Impossible Burger', 'meal', 340, '1 burger'],
  ['Slider Burger', 'meal', 200, '1 slider'],
  ['Big Mac', 'meal', 550, '1 burger'],
  ['Whopper', 'meal', 660, '1 burger'],
  ['Quarter Pounder with Cheese', 'meal', 520, '1 burger'],

  // === TACOS & MEXICAN ===
  ['Beef Taco', 'meal', 210, '1 taco'],
  ['Chicken Taco', 'meal', 190, '1 taco'],
  ['Fish Taco', 'meal', 220, '1 taco'],
  ['Carnitas Taco', 'meal', 230, '1 taco'],
  ['Al Pastor Taco', 'meal', 220, '1 taco'],
  ['Steak Taco', 'meal', 240, '1 taco'],
  ['Shrimp Taco', 'meal', 200, '1 taco'],
  ['Bean and Cheese Burrito', 'meal', 380, '1 burrito'],
  ['Chicken Burrito', 'meal', 500, '1 burrito'],
  ['Steak Burrito', 'meal', 550, '1 burrito'],
  ['Burrito Bowl', 'meal', 450, '1 bowl'],
  ['Chicken Quesadilla', 'meal', 450, '1 quesadilla'],
  ['Cheese Quesadilla', 'meal', 350, '1 quesadilla'],
  ['Nachos with Cheese', 'meal', 350, '1 serving'],
  ['Loaded Nachos', 'meal', 550, '1 serving'],
  ['Chicken Enchilada', 'meal', 280, '1 enchilada'],
  ['Beef Enchilada', 'meal', 300, '1 enchilada'],
  ['Tamale (chicken)', 'meal', 250, '1 tamale'],
  ['Chips and Salsa', 'snack', 200, '1 serving'],
  ['Chips and Guacamole', 'snack', 300, '1 serving'],
  ['Elote (Mexican Street Corn)', 'snack', 200, '1 ear'],

  // === SANDWICHES & SUBS ===
  ['Turkey Sandwich', 'meal', 350, '1 sandwich'],
  ['Ham and Cheese Sandwich', 'meal', 380, '1 sandwich'],
  ['BLT Sandwich', 'meal', 320, '1 sandwich'],
  ['Club Sandwich', 'meal', 450, '1 sandwich'],
  ['Grilled Cheese Sandwich', 'meal', 350, '1 sandwich'],
  ['Tuna Melt', 'meal', 400, '1 sandwich'],
  ['Philly Cheesesteak', 'meal', 520, '1 sub'],
  ['Italian Sub', 'meal', 550, '1 sub'],
  ['Meatball Sub', 'meal', 480, '1 sub'],
  ['Chicken Parm Sub', 'meal', 520, '1 sub'],
  ['Reuben Sandwich', 'meal', 430, '1 sandwich'],
  ['PB&J Sandwich', 'meal', 380, '1 sandwich'],
  ['Egg Salad Sandwich', 'meal', 350, '1 sandwich'],
  ['Pulled Pork Sandwich', 'meal', 480, '1 sandwich'],
  ['Cuban Sandwich', 'meal', 500, '1 sandwich'],
  ['Wrap (chicken Caesar)', 'meal', 400, '1 wrap'],
  ['Wrap (turkey avocado)', 'meal', 380, '1 wrap'],

  // === CHICKEN ===
  ['Grilled Chicken Breast', 'protein', 165, '4 oz'],
  ['Fried Chicken (breast)', 'protein', 320, '1 piece'],
  ['Fried Chicken (thigh)', 'protein', 250, '1 piece'],
  ['Fried Chicken (drumstick)', 'protein', 180, '1 piece'],
  ['Fried Chicken (wing)', 'protein', 120, '1 wing'],
  ['Chicken Tenders', 'meal', 350, '4 pieces'],
  ['Chicken Nuggets (6 pc)', 'meal', 280, '6 pieces'],
  ['Chicken Nuggets (10 pc)', 'meal', 470, '10 pieces'],
  ['Rotisserie Chicken (breast)', 'protein', 200, '4 oz'],
  ['Chicken Wings (buffalo)', 'meal', 400, '6 wings'],
  ['Chicken Wings (BBQ)', 'meal', 420, '6 wings'],
  ['Chicken Parmesan', 'meal', 480, '1 serving'],
  ['Chicken Alfredo', 'meal', 600, '1 serving'],
  ['Chicken Stir Fry', 'meal', 350, '1 serving'],
  ['Chicken Fried Rice', 'meal', 450, '1 serving'],
  ['Chicken Teriyaki', 'meal', 380, '1 serving'],
  ['Chicken Caesar Salad', 'meal', 400, '1 salad'],
  ['Chicken Pot Pie', 'meal', 450, '1 serving'],
  ['Chicken Tikka Masala', 'meal', 400, '1 serving'],
  ['Chicken Shawarma', 'meal', 350, '1 serving'],
  ['Chicken Katsu', 'meal', 420, '1 serving'],
  ['Orange Chicken', 'meal', 480, '1 serving'],
  ['General Tso Chicken', 'meal', 500, '1 serving'],
  ['Lemon Chicken', 'meal', 380, '1 serving'],
  ['Chicken Soup', 'meal', 150, '1 cup'],
  ['Chicken Noodle Soup', 'meal', 170, '1 cup'],

  // === PASTA & ITALIAN ===
  ['Spaghetti with Marinara', 'meal', 400, '1 serving'],
  ['Spaghetti and Meatballs', 'meal', 550, '1 serving'],
  ['Fettuccine Alfredo', 'meal', 550, '1 serving'],
  ['Penne Vodka', 'meal', 480, '1 serving'],
  ['Lasagna', 'meal', 450, '1 piece'],
  ['Mac and Cheese', 'meal', 400, '1 cup'],
  ['Baked Ziti', 'meal', 420, '1 serving'],
  ['Ravioli (cheese)', 'meal', 380, '1 serving'],
  ['Pesto Pasta', 'meal', 450, '1 serving'],
  ['Carbonara', 'meal', 500, '1 serving'],
  ['Eggplant Parmesan', 'meal', 380, '1 serving'],
  ['Garlic Bread', 'snack', 200, '2 slices'],
  ['Breadstick', 'snack', 140, '1 stick'],
  ['Bruschetta', 'snack', 120, '2 pieces'],
  ['Caprese Salad', 'meal', 250, '1 serving'],

  // === ASIAN ===
  ['Fried Rice', 'meal', 400, '1 serving'],
  ['Lo Mein', 'meal', 450, '1 serving'],
  ['Pad Thai', 'meal', 450, '1 serving'],
  ['Beef and Broccoli', 'meal', 350, '1 serving'],
  ['Kung Pao Chicken', 'meal', 430, '1 serving'],
  ['Sweet and Sour Chicken', 'meal', 450, '1 serving'],
  ['Egg Roll', 'snack', 180, '1 roll'],
  ['Spring Roll (fresh)', 'snack', 100, '1 roll'],
  ['Pot Stickers (pork)', 'meal', 250, '5 pieces'],
  ['Pot Stickers (chicken)', 'meal', 230, '5 pieces'],
  ['Wonton Soup', 'meal', 200, '1 cup'],
  ['Miso Soup', 'meal', 60, '1 cup'],
  ['Edamame', 'snack', 120, '1/2 cup'],
  ['Sushi Roll (California)', 'meal', 250, '6 pieces'],
  ['Sushi Roll (Spicy Tuna)', 'meal', 280, '6 pieces'],
  ['Sushi Roll (Salmon)', 'meal', 270, '6 pieces'],
  ['Sushi Roll (Dragon)', 'meal', 350, '6 pieces'],
  ['Sushi Roll (Shrimp Tempura)', 'meal', 320, '6 pieces'],
  ['Sashimi (salmon)', 'protein', 120, '4 pieces'],
  ['Teriyaki Salmon', 'meal', 380, '1 serving'],
  ['Teriyaki Chicken Bowl', 'meal', 500, '1 bowl'],
  ['Pho (beef)', 'meal', 400, '1 bowl'],
  ['Pho (chicken)', 'meal', 350, '1 bowl'],
  ['Ramen (pork)', 'meal', 500, '1 bowl'],
  ['Ramen (chicken)', 'meal', 420, '1 bowl'],
  ['Bibimbap', 'meal', 500, '1 bowl'],
  ['Korean BBQ (beef)', 'meal', 350, '1 serving'],
  ['Thai Green Curry', 'meal', 400, '1 serving'],
  ['Thai Red Curry', 'meal', 380, '1 serving'],
  ['Butter Chicken', 'meal', 440, '1 serving'],
  ['Palak Paneer', 'meal', 350, '1 serving'],
  ['Naan Bread', 'grain', 260, '1 piece'],
  ['Samosa', 'snack', 200, '1 piece'],
  ['Tikka Masala', 'meal', 400, '1 serving'],

  // === SEAFOOD ===
  ['Grilled Salmon', 'protein', 250, '4 oz'],
  ['Baked Salmon', 'protein', 230, '4 oz'],
  ['Fish and Chips', 'meal', 600, '1 serving'],
  ['Grilled Shrimp', 'protein', 100, '4 oz'],
  ['Fried Shrimp', 'meal', 350, '8 pieces'],
  ['Shrimp Scampi', 'meal', 400, '1 serving'],
  ['Crab Cake', 'meal', 200, '1 cake'],
  ['Fish Fillet (baked)', 'protein', 180, '4 oz'],
  ['Fish Fillet (fried)', 'protein', 280, '4 oz'],
  ['Tuna Steak', 'protein', 180, '4 oz'],
  ['Lobster Tail', 'protein', 140, '4 oz'],
  ['Clam Chowder', 'meal', 250, '1 cup'],
  ['Shrimp Cocktail', 'meal', 120, '6 shrimp'],

  // === BREAKFAST ===
  ['Scrambled Eggs', 'protein', 180, '2 eggs'],
  ['Fried Egg', 'protein', 90, '1 egg'],
  ['Hard Boiled Egg', 'protein', 78, '1 egg'],
  ['Bacon', 'protein', 120, '3 slices'],
  ['Turkey Bacon', 'protein', 70, '3 slices'],
  ['Sausage Links', 'protein', 180, '3 links'],
  ['Sausage Patty', 'protein', 120, '1 patty'],
  ['Pancakes', 'meal', 350, '3 pancakes'],
  ['Pancakes with Syrup', 'meal', 450, '3 pancakes'],
  ['Waffle', 'meal', 220, '1 waffle'],
  ['Waffle with Syrup', 'meal', 320, '1 waffle'],
  ['French Toast', 'meal', 350, '2 slices'],
  ['Omelette (cheese)', 'meal', 300, '1 omelette'],
  ['Omelette (veggie)', 'meal', 250, '1 omelette'],
  ['Omelette (western)', 'meal', 350, '1 omelette'],
  ['Breakfast Burrito', 'meal', 400, '1 burrito'],
  ['Breakfast Sandwich (egg and cheese)', 'meal', 350, '1 sandwich'],
  ['Breakfast Sandwich (bacon egg cheese)', 'meal', 420, '1 sandwich'],
  ['Breakfast Sandwich (sausage egg cheese)', 'meal', 450, '1 sandwich'],
  ['Eggs Benedict', 'meal', 500, '1 serving'],
  ['Avocado Toast', 'meal', 280, '1 slice'],
  ['Avocado Toast with Egg', 'meal', 370, '1 slice'],
  ['Bagel with Cream Cheese', 'meal', 350, '1 bagel'],
  ['Bagel (plain)', 'grain', 270, '1 bagel'],
  ['Toast with Butter', 'grain', 150, '2 slices'],
  ['Toast with Peanut Butter', 'meal', 280, '2 slices'],
  ['English Muffin', 'grain', 130, '1 muffin'],
  ['Croissant', 'grain', 230, '1 croissant'],
  ['Muffin (blueberry)', 'snack', 350, '1 muffin'],
  ['Muffin (bran)', 'snack', 300, '1 muffin'],
  ['Muffin (chocolate chip)', 'snack', 400, '1 muffin'],
  ['Danish Pastry', 'snack', 280, '1 danish'],
  ['Cinnamon Roll', 'snack', 420, '1 roll'],
  ['Biscuit', 'grain', 200, '1 biscuit'],
  ['Biscuits and Gravy', 'meal', 450, '1 serving'],
  ['Hash Browns', 'meal', 200, '1 serving'],
  ['Home Fries', 'meal', 250, '1 serving'],
  ['Oatmeal (plain)', 'grain', 150, '1 cup'],
  ['Oatmeal with Fruit', 'meal', 220, '1 cup'],
  ['Overnight Oats', 'meal', 300, '1 serving'],
  ['Granola', 'grain', 200, '1/2 cup'],
  ['Granola with Yogurt', 'meal', 350, '1 serving'],
  ['Cereal with Milk', 'meal', 250, '1 bowl'],
  ['Cheerios with Milk', 'meal', 200, '1 bowl'],
  ['Frosted Flakes with Milk', 'meal', 250, '1 bowl'],
  ['Greek Yogurt (plain)', 'dairy', 130, '1 cup'],
  ['Greek Yogurt (vanilla)', 'dairy', 180, '1 cup'],
  ['Greek Yogurt with Fruit', 'meal', 200, '1 cup'],
  ['Greek Yogurt Parfait', 'meal', 350, '1 parfait'],
  ['Acai Bowl', 'meal', 400, '1 bowl'],
  ['Smoothie Bowl', 'meal', 350, '1 bowl'],
  ['Fruit Smoothie', 'beverage', 250, '16 oz'],
  ['Green Smoothie', 'beverage', 200, '16 oz'],
  ['Protein Smoothie', 'beverage', 300, '16 oz'],

  // === SALADS ===
  ['Caesar Salad', 'meal', 300, '1 salad'],
  ['Garden Salad', 'meal', 150, '1 salad'],
  ['Cobb Salad', 'meal', 450, '1 salad'],
  ['Greek Salad', 'meal', 250, '1 salad'],
  ['Southwest Salad', 'meal', 400, '1 salad'],
  ['Asian Chicken Salad', 'meal', 380, '1 salad'],
  ['Taco Salad', 'meal', 500, '1 salad'],
  ['Spinach Salad', 'meal', 200, '1 salad'],
  ['Kale Salad', 'meal', 250, '1 salad'],
  ['Quinoa Salad', 'meal', 300, '1 serving'],
  ['Pasta Salad', 'meal', 300, '1 cup'],
  ['Potato Salad', 'meal', 250, '1 cup'],
  ['Coleslaw', 'meal', 180, '1 cup'],
  ['Side Salad', 'meal', 100, '1 salad'],

  // === SOUPS ===
  ['Tomato Soup', 'meal', 150, '1 cup'],
  ['Chicken Tortilla Soup', 'meal', 200, '1 cup'],
  ['Minestrone Soup', 'meal', 150, '1 cup'],
  ['Broccoli Cheddar Soup', 'meal', 280, '1 cup'],
  ['Chili (beef)', 'meal', 300, '1 cup'],
  ['Chili (turkey)', 'meal', 250, '1 cup'],
  ['Vegetable Soup', 'meal', 120, '1 cup'],
  ['French Onion Soup', 'meal', 300, '1 bowl'],
  ['Beef Stew', 'meal', 250, '1 cup'],
  ['Lentil Soup', 'meal', 180, '1 cup'],
  ['Split Pea Soup', 'meal', 190, '1 cup'],
  ['Cream of Mushroom Soup', 'meal', 200, '1 cup'],
  ['New England Clam Chowder', 'meal', 250, '1 cup'],

  // === SIDES ===
  ['French Fries', 'meal', 365, '1 medium'],
  ['Curly Fries', 'meal', 380, '1 serving'],
  ['Sweet Potato Fries', 'meal', 300, '1 serving'],
  ['Onion Rings', 'meal', 350, '1 serving'],
  ['Mashed Potatoes', 'meal', 200, '1 cup'],
  ['Baked Potato (plain)', 'meal', 160, '1 potato'],
  ['Loaded Baked Potato', 'meal', 400, '1 potato'],
  ['Mozzarella Sticks', 'snack', 350, '5 sticks'],
  ['Jalapeno Poppers', 'snack', 300, '5 pieces'],
  ['Fried Pickles', 'snack', 250, '1 serving'],
  ['Corn on the Cob', 'vegetable', 130, '1 ear'],
  ['Cornbread', 'grain', 180, '1 piece'],
  ['Dinner Roll', 'grain', 110, '1 roll'],
  ['Baked Beans', 'meal', 240, '1 cup'],
  ['Cooked Rice (white)', 'grain', 200, '1 cup'],
  ['Cooked Rice (brown)', 'grain', 220, '1 cup'],
  ['Fried Rice (side)', 'grain', 250, '1 cup'],
  ['Steamed Broccoli', 'vegetable', 55, '1 cup'],
  ['Roasted Vegetables', 'vegetable', 150, '1 cup'],
  ['Sauteed Spinach', 'vegetable', 80, '1 cup'],
  ['Green Beans', 'vegetable', 35, '1 cup'],
  ['Sweet Potato (baked)', 'vegetable', 115, '1 potato'],
  ['Macaroni Salad', 'meal', 280, '1 cup'],
  ['Hummus', 'snack', 100, '1/4 cup'],

  // === FAST FOOD ===
  ['Chicken Sandwich (Chick-fil-A style)', 'meal', 440, '1 sandwich'],
  ['Spicy Chicken Sandwich', 'meal', 480, '1 sandwich'],
  ['Crispy Chicken Sandwich', 'meal', 500, '1 sandwich'],
  ['Fish Sandwich', 'meal', 380, '1 sandwich'],
  ['Hot Dog', 'meal', 280, '1 hot dog'],
  ['Corn Dog', 'meal', 250, '1 corn dog'],
  ['Chicken Wrap', 'meal', 380, '1 wrap'],
  ['Gyro', 'meal', 500, '1 gyro'],
  ['Falafel Wrap', 'meal', 400, '1 wrap'],
  ['Kebab Plate', 'meal', 450, '1 plate'],
  ['Popcorn Chicken', 'snack', 350, '1 serving'],

  // === STEAK & BBQ ===
  ['Ribeye Steak', 'protein', 400, '8 oz'],
  ['Sirloin Steak', 'protein', 300, '8 oz'],
  ['Filet Mignon', 'protein', 280, '6 oz'],
  ['T-Bone Steak', 'protein', 380, '8 oz'],
  ['NY Strip Steak', 'protein', 360, '8 oz'],
  ['BBQ Ribs', 'meal', 500, '4 ribs'],
  ['Pulled Pork', 'protein', 250, '4 oz'],
  ['Brisket', 'protein', 300, '4 oz'],
  ['Meatloaf', 'meal', 350, '1 slice'],
  ['Pot Roast', 'meal', 300, '1 serving'],
  ['Beef Tacos (ground)', 'meal', 400, '2 tacos'],
  ['Steak and Potatoes', 'meal', 550, '1 serving'],

  // === SNACKS ===
  ['Protein Bar', 'snack', 220, '1 bar'],
  ['Granola Bar', 'snack', 180, '1 bar'],
  ['Kind Bar', 'snack', 200, '1 bar'],
  ['Clif Bar', 'snack', 250, '1 bar'],
  ['Trail Mix', 'snack', 300, '1/4 cup'],
  ['Mixed Nuts', 'snack', 200, '1/4 cup'],
  ['Almonds', 'snack', 170, '1/4 cup'],
  ['Peanuts', 'snack', 210, '1/4 cup'],
  ['Cashews', 'snack', 190, '1/4 cup'],
  ['Peanut Butter', 'snack', 190, '2 tbsp'],
  ['Almond Butter', 'snack', 200, '2 tbsp'],
  ['Cheese and Crackers', 'snack', 200, '1 serving'],
  ['Goldfish Crackers', 'snack', 140, '55 pieces'],
  ['Pretzels', 'snack', 110, '1 oz'],
  ['Tortilla Chips', 'snack', 150, '1 oz'],
  ['Potato Chips', 'snack', 160, '1 oz'],
  ['Doritos', 'snack', 140, '1 oz'],
  ['Popcorn (buttered)', 'snack', 180, '3 cups'],
  ['Popcorn (air-popped)', 'snack', 100, '3 cups'],
  ['Beef Jerky', 'snack', 120, '1 oz'],
  ['String Cheese', 'snack', 80, '1 stick'],
  ['Cottage Cheese', 'dairy', 110, '1/2 cup'],
  ['Celery with Peanut Butter', 'snack', 180, '3 stalks'],
  ['Carrots with Ranch', 'snack', 150, '1 serving'],
  ['Apple with Peanut Butter', 'snack', 270, '1 apple'],
  ['Yogurt Cup', 'snack', 150, '1 cup'],
  ['Rice Cake', 'snack', 35, '1 cake'],
  ['Fruit Cup', 'snack', 70, '1 cup'],

  // === DESSERTS ===
  ['Chocolate Chip Cookie', 'snack', 200, '1 cookie'],
  ['Brownie', 'snack', 260, '1 brownie'],
  ['Slice of Cake (chocolate)', 'snack', 350, '1 slice'],
  ['Slice of Cake (vanilla)', 'snack', 320, '1 slice'],
  ['Slice of Cheesecake', 'snack', 400, '1 slice'],
  ['Donut (glazed)', 'snack', 260, '1 donut'],
  ['Donut (chocolate)', 'snack', 300, '1 donut'],
  ['Donut (jelly-filled)', 'snack', 280, '1 donut'],
  ['Ice Cream (vanilla)', 'snack', 270, '1 cup'],
  ['Ice Cream (chocolate)', 'snack', 290, '1 cup'],
  ['Ice Cream Cone', 'snack', 200, '1 cone'],
  ['Ice Cream Sundae', 'snack', 400, '1 sundae'],
  ['Milkshake (chocolate)', 'beverage', 500, '16 oz'],
  ['Milkshake (vanilla)', 'beverage', 450, '16 oz'],
  ['Milkshake (strawberry)', 'beverage', 460, '16 oz'],
  ['Pie (apple)', 'snack', 300, '1 slice'],
  ['Pie (pumpkin)', 'snack', 280, '1 slice'],
  ['Pie (cherry)', 'snack', 310, '1 slice'],
  ['Pie (pecan)', 'snack', 450, '1 slice'],
  ['Churro', 'snack', 200, '1 churro'],
  ['Cinnamon Sugar Pretzel', 'snack', 350, '1 pretzel'],
  ['Chocolate Bar', 'snack', 230, '1 bar'],
  ['Candy Bar (Snickers)', 'snack', 250, '1 bar'],
  ['Candy Bar (Kit Kat)', 'snack', 210, '1 bar'],
  ['Candy Bar (Reeses)', 'snack', 210, '2 cups'],
  ['Gummy Bears', 'snack', 140, '1 serving'],
  ['M&Ms', 'snack', 240, '1 bag'],
  ['Skittles', 'snack', 230, '1 bag'],

  // === DRINKS ===
  ['Coca-Cola', 'beverage', 140, '12 oz'],
  ['Diet Coke', 'beverage', 0, '12 oz'],
  ['Sprite', 'beverage', 140, '12 oz'],
  ['Ginger Ale', 'beverage', 130, '12 oz'],
  ['Root Beer', 'beverage', 150, '12 oz'],
  ['Lemonade', 'beverage', 120, '12 oz'],
  ['Iced Tea (sweetened)', 'beverage', 100, '12 oz'],
  ['Iced Tea (unsweetened)', 'beverage', 5, '12 oz'],
  ['Orange Juice', 'beverage', 110, '8 oz'],
  ['Apple Juice', 'beverage', 120, '8 oz'],
  ['Cranberry Juice', 'beverage', 130, '8 oz'],
  ['Coffee (black)', 'beverage', 5, '8 oz'],
  ['Coffee with Cream and Sugar', 'beverage', 60, '8 oz'],
  ['Latte', 'beverage', 190, '16 oz'],
  ['Iced Latte', 'beverage', 180, '16 oz'],
  ['Cappuccino', 'beverage', 120, '12 oz'],
  ['Mocha', 'beverage', 300, '16 oz'],
  ['Frappuccino', 'beverage', 380, '16 oz'],
  ['Chai Latte', 'beverage', 240, '16 oz'],
  ['Hot Chocolate', 'beverage', 200, '12 oz'],
  ['Gatorade', 'beverage', 80, '12 oz'],
  ['Red Bull', 'beverage', 110, '8.4 oz'],
  ['Monster Energy', 'beverage', 110, '8 oz'],
  ['Protein Shake', 'beverage', 200, '1 shake'],
  ['Whole Milk', 'dairy', 150, '1 cup'],
  ['2% Milk', 'dairy', 125, '1 cup'],
  ['Skim Milk', 'dairy', 90, '1 cup'],
  ['Almond Milk', 'dairy', 40, '1 cup'],
  ['Oat Milk', 'dairy', 120, '1 cup'],
  ['Chocolate Milk', 'dairy', 200, '1 cup'],
  ['Beer (regular)', 'beverage', 150, '12 oz'],
  ['Beer (light)', 'beverage', 100, '12 oz'],
  ['Glass of Wine (red)', 'beverage', 125, '5 oz'],
  ['Glass of Wine (white)', 'beverage', 120, '5 oz'],
  ['Margarita', 'beverage', 280, '8 oz'],

  // === FRUITS ===
  ['Apple', 'fruit', 95, '1 medium'],
  ['Banana', 'fruit', 105, '1 medium'],
  ['Orange', 'fruit', 65, '1 medium'],
  ['Grapes', 'fruit', 60, '1 cup'],
  ['Strawberries', 'fruit', 50, '1 cup'],
  ['Blueberries', 'fruit', 85, '1 cup'],
  ['Raspberries', 'fruit', 65, '1 cup'],
  ['Watermelon', 'fruit', 45, '1 cup'],
  ['Pineapple', 'fruit', 80, '1 cup'],
  ['Mango', 'fruit', 100, '1 cup'],
  ['Peach', 'fruit', 60, '1 medium'],
  ['Pear', 'fruit', 100, '1 medium'],
  ['Avocado', 'fruit', 240, '1 whole'],
  ['Avocado (half)', 'fruit', 120, '1/2'],
  ['Clementine', 'fruit', 35, '1 fruit'],
  ['Kiwi', 'fruit', 42, '1 fruit'],
  ['Cherries', 'fruit', 90, '1 cup'],
  ['Cantaloupe', 'fruit', 55, '1 cup'],
  ['Mixed Berries', 'fruit', 70, '1 cup'],
  ['Dried Fruit Mix', 'snack', 130, '1/4 cup'],
];

exports.up = async (pgm) => {
  // Remove duplicates from existing data
  pgm.sql(`
    DELETE FROM food_database a
    USING food_database b
    WHERE a.id > b.id
      AND a.name = b.name
      AND a.calories_per_serving = b.calories_per_serving
      AND a.serving_size = b.serving_size;
  `);

  // Insert new foods (skip if name already exists)
  for (const [name, category, calories, serving] of foods) {
    pgm.sql(`
      INSERT INTO food_database (name, category, calories_per_serving, serving_size)
      SELECT '${name.replace(/'/g, "''")}', '${category}', ${calories}, '${serving}'
      WHERE NOT EXISTS (
        SELECT 1 FROM food_database WHERE LOWER(name) = LOWER('${name.replace(/'/g, "''")}')
      );
    `);
  }
};

exports.down = (pgm) => {
  // Can't easily undo this
};
