require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const pool = require('../config/db');

const foods = [
  // ============================================================
  // PROTEIN (75 items)
  // ============================================================
  ['Chicken Breast (grilled)', 'protein', 165, '4 oz'],
  ['Chicken Breast (fried)', 'protein', 260, '4 oz'],
  ['Chicken Thigh (bone-in, skin-on)', 'protein', 230, '4 oz'],
  ['Chicken Thigh (boneless, skinless)', 'protein', 180, '4 oz'],
  ['Chicken Drumstick', 'protein', 175, '1 drumstick'],
  ['Chicken Wing', 'protein', 100, '1 wing'],
  ['Rotisserie Chicken', 'protein', 190, '4 oz'],
  ['Chicken Tender', 'protein', 90, '1 tender'],
  ['Ground Chicken', 'protein', 170, '4 oz'],
  ['Turkey Breast (roasted)', 'protein', 150, '4 oz'],
  ['Ground Turkey (93% lean)', 'protein', 170, '4 oz'],
  ['Ground Turkey (85% lean)', 'protein', 200, '4 oz'],
  ['Turkey Sausage', 'protein', 140, '1 link'],
  ['Turkey Bacon', 'protein', 60, '2 slices'],
  ['Turkey Deli Meat', 'protein', 60, '2 oz'],
  ['Salmon Fillet (Atlantic)', 'protein', 230, '4 oz'],
  ['Salmon (canned)', 'protein', 160, '4 oz'],
  ['Smoked Salmon', 'protein', 130, '3 oz'],
  ['Tuna (canned in water)', 'protein', 100, '4 oz'],
  ['Tuna (canned in oil)', 'protein', 160, '4 oz'],
  ['Tuna Steak', 'protein', 150, '4 oz'],
  ['Shrimp', 'protein', 100, '4 oz'],
  ['Cod Fillet', 'protein', 90, '4 oz'],
  ['Tilapia Fillet', 'protein', 110, '4 oz'],
  ['Halibut', 'protein', 120, '4 oz'],
  ['Mahi Mahi', 'protein', 100, '4 oz'],
  ['Catfish', 'protein', 150, '4 oz'],
  ['Sardines (canned)', 'protein', 190, '1 can (3.75 oz)'],
  ['Crab Meat', 'protein', 80, '4 oz'],
  ['Lobster Tail', 'protein', 130, '1 tail (5 oz)'],
  ['Scallops', 'protein', 95, '4 oz'],
  ['Clams', 'protein', 75, '4 oz'],
  ['Ground Beef (90% lean)', 'protein', 200, '4 oz'],
  ['Ground Beef (80% lean)', 'protein', 280, '4 oz'],
  ['Ground Beef (73% lean)', 'protein', 310, '4 oz'],
  ['Sirloin Steak', 'protein', 210, '4 oz'],
  ['Ribeye Steak', 'protein', 290, '4 oz'],
  ['New York Strip Steak', 'protein', 250, '4 oz'],
  ['Filet Mignon', 'protein', 230, '4 oz'],
  ['Flank Steak', 'protein', 200, '4 oz'],
  ['Beef Brisket', 'protein', 330, '4 oz'],
  ['Corned Beef', 'protein', 210, '4 oz'],
  ['Beef Jerky', 'protein', 80, '1 oz'],
  ['Pork Chop (bone-in)', 'protein', 210, '4 oz'],
  ['Pork Chop (boneless)', 'protein', 190, '4 oz'],
  ['Pork Tenderloin', 'protein', 140, '4 oz'],
  ['Pulled Pork', 'protein', 240, '4 oz'],
  ['Bacon', 'protein', 90, '2 slices'],
  ['Canadian Bacon', 'protein', 70, '2 slices'],
  ['Ham (deli sliced)', 'protein', 60, '2 oz'],
  ['Ham Steak', 'protein', 160, '4 oz'],
  ['Pork Sausage', 'protein', 200, '1 link'],
  ['Italian Sausage', 'protein', 230, '1 link'],
  ['Bratwurst', 'protein', 280, '1 link'],
  ['Hot Dog (beef)', 'protein', 190, '1 frank'],
  ['Hot Dog (turkey)', 'protein', 100, '1 frank'],
  ['Pepperoni', 'protein', 140, '1 oz'],
  ['Salami', 'protein', 120, '1 oz'],
  ['Lamb Chop', 'protein', 230, '4 oz'],
  ['Ground Lamb', 'protein', 280, '4 oz'],
  ['Eggs (whole, large)', 'protein', 70, '1 egg'],
  ['Egg Whites', 'protein', 17, '1 white'],
  ['Hard Boiled Egg', 'protein', 78, '1 egg'],
  ['Tofu (firm)', 'protein', 90, '4 oz'],
  ['Tofu (silken)', 'protein', 60, '4 oz'],
  ['Tempeh', 'protein', 190, '4 oz'],
  ['Edamame (shelled)', 'protein', 120, '1/2 cup'],
  ['Black Beans (cooked)', 'protein', 115, '1/2 cup'],
  ['Chickpeas (cooked)', 'protein', 135, '1/2 cup'],
  ['Lentils (cooked)', 'protein', 115, '1/2 cup'],
  ['Kidney Beans (cooked)', 'protein', 110, '1/2 cup'],
  ['Pinto Beans (cooked)', 'protein', 120, '1/2 cup'],
  ['Bison (ground)', 'protein', 190, '4 oz'],
  ['Venison', 'protein', 160, '4 oz'],
  ['Duck Breast', 'protein', 230, '4 oz'],

  // ============================================================
  // GRAIN (70 items)
  // ============================================================
  ['White Rice (cooked)', 'grain', 205, '1 cup'],
  ['Brown Rice (cooked)', 'grain', 215, '1 cup'],
  ['Jasmine Rice (cooked)', 'grain', 210, '1 cup'],
  ['Basmati Rice (cooked)', 'grain', 200, '1 cup'],
  ['Wild Rice (cooked)', 'grain', 165, '1 cup'],
  ['Fried Rice', 'grain', 235, '1 cup'],
  ['Rice Pilaf', 'grain', 200, '1 cup'],
  ['Spaghetti (cooked)', 'grain', 220, '1 cup'],
  ['Penne Pasta (cooked)', 'grain', 220, '1 cup'],
  ['Fettuccine (cooked)', 'grain', 220, '1 cup'],
  ['Whole Wheat Pasta (cooked)', 'grain', 175, '1 cup'],
  ['Macaroni (cooked)', 'grain', 220, '1 cup'],
  ['Egg Noodles (cooked)', 'grain', 220, '1 cup'],
  ['Ramen Noodles (cooked)', 'grain', 190, '1 cup'],
  ['Rice Noodles (cooked)', 'grain', 190, '1 cup'],
  ['Udon Noodles (cooked)', 'grain', 210, '1 cup'],
  ['Soba Noodles (cooked)', 'grain', 115, '1 cup'],
  ['Couscous (cooked)', 'grain', 175, '1 cup'],
  ['Quinoa (cooked)', 'grain', 220, '1 cup'],
  ['Bulgur (cooked)', 'grain', 150, '1 cup'],
  ['Barley (cooked)', 'grain', 195, '1 cup'],
  ['Farro (cooked)', 'grain', 200, '1 cup'],
  ['Polenta (cooked)', 'grain', 145, '1 cup'],
  ['Oatmeal (cooked)', 'grain', 155, '1 cup'],
  ['Instant Oatmeal (packet)', 'grain', 130, '1 packet'],
  ['Steel Cut Oats (cooked)', 'grain', 150, '1 cup'],
  ['Overnight Oats', 'grain', 210, '1 cup'],
  ['Grits (cooked)', 'grain', 145, '1 cup'],
  ['Cream of Wheat (cooked)', 'grain', 130, '1 cup'],
  ['White Bread', 'grain', 75, '1 slice'],
  ['Whole Wheat Bread', 'grain', 80, '1 slice'],
  ['Sourdough Bread', 'grain', 90, '1 slice'],
  ['Rye Bread', 'grain', 85, '1 slice'],
  ['Multigrain Bread', 'grain', 80, '1 slice'],
  ['Ciabatta Bread', 'grain', 120, '1 slice'],
  ['French Baguette', 'grain', 140, '2 oz'],
  ['Pita Bread (white)', 'grain', 170, '1 pita (6.5 in)'],
  ['Pita Bread (whole wheat)', 'grain', 150, '1 pita (6.5 in)'],
  ['Naan Bread', 'grain', 260, '1 piece'],
  ['Corn Tortilla', 'grain', 55, '1 tortilla (6 in)'],
  ['Flour Tortilla (small)', 'grain', 90, '1 tortilla (6 in)'],
  ['Flour Tortilla (large)', 'grain', 210, '1 tortilla (10 in)'],
  ['Whole Wheat Tortilla', 'grain', 130, '1 tortilla (8 in)'],
  ['English Muffin', 'grain', 130, '1 muffin'],
  ['Bagel (plain)', 'grain', 270, '1 bagel'],
  ['Bagel (everything)', 'grain', 280, '1 bagel'],
  ['Croissant', 'grain', 230, '1 croissant'],
  ['Dinner Roll', 'grain', 90, '1 roll'],
  ['Hamburger Bun', 'grain', 140, '1 bun'],
  ['Hot Dog Bun', 'grain', 120, '1 bun'],
  ['Cornbread', 'grain', 175, '1 piece (2.5 in square)'],
  ['Biscuit', 'grain', 180, '1 biscuit'],
  ['Pancake', 'grain', 90, '1 pancake (4 in)'],
  ['Waffle', 'grain', 220, '1 waffle (7 in)'],
  ['French Toast', 'grain', 150, '1 slice'],
  ['Granola', 'grain', 210, '1/2 cup'],
  ['Cheerios', 'grain', 100, '1 cup'],
  ['Corn Flakes', 'grain', 100, '1 cup'],
  ['Frosted Flakes', 'grain', 140, '1 cup'],
  ['Honey Nut Cheerios', 'grain', 140, '1 cup'],
  ['Special K', 'grain', 120, '1 cup'],
  ['Raisin Bran', 'grain', 190, '1 cup'],
  ['Rice Krispies', 'grain', 130, '1.25 cup'],
  ['Grape Nuts', 'grain', 200, '1/2 cup'],
  ['Muesli', 'grain', 220, '2/3 cup'],
  ['Cream of Rice (cooked)', 'grain', 125, '1 cup'],
  ['Wheat Germ', 'grain', 50, '2 tbsp'],
  ['Breadstick', 'grain', 40, '1 stick'],
  ['Cracklin Oat Bran', 'grain', 200, '3/4 cup'],
  ['Taco Shell (hard)', 'grain', 60, '1 shell'],

  // ============================================================
  // VEGETABLE (80 items)
  // ============================================================
  ['Broccoli (raw)', 'vegetable', 30, '1 cup chopped'],
  ['Broccoli (steamed)', 'vegetable', 55, '1 cup chopped'],
  ['Spinach (raw)', 'vegetable', 7, '1 cup'],
  ['Spinach (cooked)', 'vegetable', 40, '1 cup'],
  ['Kale (raw)', 'vegetable', 35, '1 cup chopped'],
  ['Kale (cooked)', 'vegetable', 35, '1 cup chopped'],
  ['Romaine Lettuce', 'vegetable', 10, '1 cup shredded'],
  ['Iceberg Lettuce', 'vegetable', 10, '1 cup shredded'],
  ['Mixed Greens', 'vegetable', 10, '1 cup'],
  ['Arugula', 'vegetable', 5, '1 cup'],
  ['Carrots (raw)', 'vegetable', 25, '1 medium'],
  ['Carrots (cooked)', 'vegetable', 55, '1 cup sliced'],
  ['Baby Carrots', 'vegetable', 35, '3 oz (about 8)'],
  ['Celery', 'vegetable', 10, '2 stalks'],
  ['Cucumber', 'vegetable', 15, '1/2 medium'],
  ['Bell Pepper (green)', 'vegetable', 25, '1 medium'],
  ['Bell Pepper (red)', 'vegetable', 30, '1 medium'],
  ['Bell Pepper (yellow)', 'vegetable', 30, '1 medium'],
  ['Tomato (raw)', 'vegetable', 22, '1 medium'],
  ['Cherry Tomatoes', 'vegetable', 25, '1 cup'],
  ['Roma Tomato', 'vegetable', 15, '1 tomato'],
  ['Tomato (canned, diced)', 'vegetable', 30, '1/2 cup'],
  ['Sun-Dried Tomatoes', 'vegetable', 70, '1/4 cup'],
  ['Onion (raw)', 'vegetable', 45, '1 medium'],
  ['Green Onion', 'vegetable', 5, '1 stalk'],
  ['Red Onion', 'vegetable', 45, '1 medium'],
  ['Garlic', 'vegetable', 5, '1 clove'],
  ['Mushrooms (raw)', 'vegetable', 15, '1 cup sliced'],
  ['Mushrooms (cooked)', 'vegetable', 28, '1 cup sliced'],
  ['Portobello Mushroom', 'vegetable', 35, '1 cap'],
  ['Zucchini', 'vegetable', 20, '1 medium'],
  ['Yellow Squash', 'vegetable', 20, '1 medium'],
  ['Butternut Squash (cooked)', 'vegetable', 80, '1 cup cubed'],
  ['Acorn Squash (cooked)', 'vegetable', 115, '1 cup cubed'],
  ['Spaghetti Squash (cooked)', 'vegetable', 40, '1 cup'],
  ['Sweet Potato (baked)', 'vegetable', 100, '1 medium'],
  ['Sweet Potato (mashed)', 'vegetable', 250, '1 cup'],
  ['Russet Potato (baked)', 'vegetable', 160, '1 medium'],
  ['Red Potato (boiled)', 'vegetable', 150, '1 medium'],
  ['Mashed Potatoes', 'vegetable', 210, '1 cup'],
  ['French Fries (baked)', 'vegetable', 170, '3 oz'],
  ['Corn on the Cob', 'vegetable', 90, '1 ear'],
  ['Corn (canned)', 'vegetable', 65, '1/2 cup'],
  ['Green Beans (fresh)', 'vegetable', 30, '1 cup'],
  ['Green Beans (canned)', 'vegetable', 20, '1/2 cup'],
  ['Peas (green, cooked)', 'vegetable', 65, '1/2 cup'],
  ['Snap Peas', 'vegetable', 25, '1 cup'],
  ['Snow Peas', 'vegetable', 25, '1 cup'],
  ['Brussels Sprouts', 'vegetable', 55, '1 cup'],
  ['Cauliflower (raw)', 'vegetable', 25, '1 cup'],
  ['Cauliflower (cooked)', 'vegetable', 30, '1 cup'],
  ['Asparagus', 'vegetable', 25, '6 spears'],
  ['Artichoke', 'vegetable', 60, '1 medium'],
  ['Eggplant (cooked)', 'vegetable', 35, '1 cup cubed'],
  ['Cabbage (raw)', 'vegetable', 20, '1 cup shredded'],
  ['Cabbage (cooked)', 'vegetable', 35, '1 cup shredded'],
  ['Coleslaw', 'vegetable', 80, '1/2 cup'],
  ['Sauerkraut', 'vegetable', 15, '1/2 cup'],
  ['Beets (cooked)', 'vegetable', 60, '1 cup sliced'],
  ['Radish', 'vegetable', 1, '1 radish'],
  ['Turnip (cooked)', 'vegetable', 35, '1 cup cubed'],
  ['Parsnip (cooked)', 'vegetable', 110, '1 cup sliced'],
  ['Jalape\u00f1o Pepper', 'vegetable', 4, '1 pepper'],
  ['Serrano Pepper', 'vegetable', 2, '1 pepper'],
  ['Poblano Pepper', 'vegetable', 15, '1 pepper'],
  ['Okra (cooked)', 'vegetable', 35, '1 cup sliced'],
  ['Leek', 'vegetable', 55, '1 leek'],
  ['Fennel Bulb', 'vegetable', 25, '1/2 cup sliced'],
  ['Watercress', 'vegetable', 4, '1 cup'],
  ['Bok Choy', 'vegetable', 10, '1 cup shredded'],
  ['Swiss Chard (cooked)', 'vegetable', 35, '1 cup'],
  ['Collard Greens (cooked)', 'vegetable', 50, '1 cup'],
  ['Turnip Greens (cooked)', 'vegetable', 30, '1 cup'],
  ['Jicama', 'vegetable', 25, '1/2 cup sliced'],
  ['Bean Sprouts', 'vegetable', 25, '1 cup'],
  ['Water Chestnuts', 'vegetable', 35, '1/2 cup sliced'],
  ['Bamboo Shoots', 'vegetable', 15, '1/2 cup sliced'],
  ['Hearts of Palm', 'vegetable', 20, '1/2 cup'],
  ['Seaweed (nori, dried)', 'vegetable', 5, '1 sheet'],
  ['Kimchi', 'vegetable', 15, '1/2 cup'],

  // ============================================================
  // FRUIT (65 items)
  // ============================================================
  ['Apple', 'fruit', 95, '1 medium'],
  ['Banana', 'fruit', 105, '1 medium'],
  ['Orange', 'fruit', 62, '1 medium'],
  ['Grapes (red)', 'fruit', 105, '1 cup'],
  ['Grapes (green)', 'fruit', 100, '1 cup'],
  ['Strawberries', 'fruit', 50, '1 cup'],
  ['Blueberries', 'fruit', 85, '1 cup'],
  ['Raspberries', 'fruit', 65, '1 cup'],
  ['Blackberries', 'fruit', 60, '1 cup'],
  ['Watermelon', 'fruit', 45, '1 cup diced'],
  ['Cantaloupe', 'fruit', 55, '1 cup diced'],
  ['Honeydew Melon', 'fruit', 60, '1 cup diced'],
  ['Pineapple', 'fruit', 80, '1 cup chunks'],
  ['Mango', 'fruit', 100, '1 cup sliced'],
  ['Papaya', 'fruit', 55, '1 cup cubed'],
  ['Kiwi', 'fruit', 42, '1 medium'],
  ['Peach', 'fruit', 60, '1 medium'],
  ['Nectarine', 'fruit', 60, '1 medium'],
  ['Plum', 'fruit', 30, '1 medium'],
  ['Pear', 'fruit', 100, '1 medium'],
  ['Cherries (sweet)', 'fruit', 90, '1 cup'],
  ['Apricot', 'fruit', 17, '1 apricot'],
  ['Grapefruit', 'fruit', 52, '1/2 medium'],
  ['Tangerine', 'fruit', 47, '1 medium'],
  ['Clementine', 'fruit', 35, '1 clementine'],
  ['Lemon', 'fruit', 17, '1 medium'],
  ['Lime', 'fruit', 20, '1 medium'],
  ['Pomegranate Seeds', 'fruit', 72, '1/2 cup'],
  ['Fig (fresh)', 'fruit', 37, '1 medium'],
  ['Dates (Medjool)', 'fruit', 65, '1 date'],
  ['Dried Cranberries', 'fruit', 130, '1/4 cup'],
  ['Raisins', 'fruit', 130, '1/4 cup'],
  ['Dried Apricots', 'fruit', 80, '1/4 cup'],
  ['Dried Mango', 'fruit', 120, '1/4 cup'],
  ['Prunes', 'fruit', 100, '1/4 cup'],
  ['Coconut (fresh)', 'fruit', 140, '1/4 cup shredded'],
  ['Coconut (dried, shredded)', 'fruit', 185, '1/4 cup'],
  ['Avocado', 'fruit', 240, '1 medium'],
  ['Plantain (cooked)', 'fruit', 180, '1 cup sliced'],
  ['Passion Fruit', 'fruit', 17, '1 fruit'],
  ['Guava', 'fruit', 37, '1 fruit'],
  ['Star Fruit', 'fruit', 30, '1 medium'],
  ['Dragon Fruit', 'fruit', 60, '1 medium'],
  ['Lychee', 'fruit', 65, '1/2 cup'],
  ['Persimmon', 'fruit', 118, '1 fruit'],
  ['Jackfruit', 'fruit', 95, '1 cup sliced'],
  ['Kumquat', 'fruit', 13, '1 fruit'],
  ['Cranberries (fresh)', 'fruit', 45, '1 cup'],
  ['Frozen Strawberries', 'fruit', 75, '1 cup'],
  ['Frozen Blueberries', 'fruit', 80, '1 cup'],
  ['Frozen Mixed Berries', 'fruit', 70, '1 cup'],
  ['Frozen Mango Chunks', 'fruit', 100, '1 cup'],
  ['Frozen Peach Slices', 'fruit', 60, '1 cup'],
  ['Applesauce (unsweetened)', 'fruit', 50, '1/2 cup'],
  ['Applesauce (sweetened)', 'fruit', 95, '1/2 cup'],
  ['Mandarin Oranges (canned)', 'fruit', 70, '1/2 cup'],
  ['Pineapple (canned in juice)', 'fruit', 75, '1/2 cup'],
  ['Peaches (canned in juice)', 'fruit', 55, '1/2 cup'],
  ['Fruit Cocktail (canned)', 'fruit', 55, '1/2 cup'],
  ['Banana Chips', 'fruit', 150, '1 oz'],
  ['Acai (frozen, unsweetened)', 'fruit', 70, '1 packet (100g)'],
  ['Goji Berries (dried)', 'fruit', 100, '1 oz'],
  ['Mulberries', 'fruit', 60, '1 cup'],
  ['Breadfruit', 'fruit', 225, '1 cup'],
  ['Tamarind', 'fruit', 140, '1/2 cup pulp'],

  // ============================================================
  // DAIRY (60 items)
  // ============================================================
  ['Whole Milk', 'dairy', 150, '1 cup'],
  ['2% Milk', 'dairy', 125, '1 cup'],
  ['1% Milk', 'dairy', 105, '1 cup'],
  ['Skim Milk', 'dairy', 85, '1 cup'],
  ['Chocolate Milk (whole)', 'dairy', 210, '1 cup'],
  ['Chocolate Milk (1%)', 'dairy', 160, '1 cup'],
  ['Buttermilk', 'dairy', 100, '1 cup'],
  ['Heavy Cream', 'dairy', 50, '1 tbsp'],
  ['Half and Half', 'dairy', 20, '1 tbsp'],
  ['Whipped Cream', 'dairy', 25, '2 tbsp'],
  ['Sour Cream', 'dairy', 60, '2 tbsp'],
  ['Sour Cream (light)', 'dairy', 40, '2 tbsp'],
  ['Cream Cheese', 'dairy', 100, '2 tbsp'],
  ['Cream Cheese (light)', 'dairy', 60, '2 tbsp'],
  ['Cheddar Cheese', 'dairy', 115, '1 oz'],
  ['Sharp Cheddar Cheese', 'dairy', 115, '1 oz'],
  ['Mozzarella Cheese (whole milk)', 'dairy', 85, '1 oz'],
  ['Mozzarella Cheese (part-skim)', 'dairy', 70, '1 oz'],
  ['Fresh Mozzarella', 'dairy', 70, '1 oz'],
  ['Swiss Cheese', 'dairy', 110, '1 oz'],
  ['Provolone Cheese', 'dairy', 100, '1 oz'],
  ['Pepper Jack Cheese', 'dairy', 110, '1 oz'],
  ['Colby Jack Cheese', 'dairy', 110, '1 oz'],
  ['American Cheese', 'dairy', 95, '1 slice'],
  ['Monterey Jack Cheese', 'dairy', 105, '1 oz'],
  ['Gouda Cheese', 'dairy', 100, '1 oz'],
  ['Brie Cheese', 'dairy', 95, '1 oz'],
  ['Parmesan Cheese (grated)', 'dairy', 22, '1 tbsp'],
  ['Parmesan Cheese (block)', 'dairy', 110, '1 oz'],
  ['Feta Cheese', 'dairy', 75, '1 oz'],
  ['Blue Cheese', 'dairy', 100, '1 oz'],
  ['Goat Cheese', 'dairy', 75, '1 oz'],
  ['Ricotta Cheese (whole milk)', 'dairy', 215, '1/2 cup'],
  ['Ricotta Cheese (part-skim)', 'dairy', 170, '1/2 cup'],
  ['Cottage Cheese (full-fat)', 'dairy', 220, '1 cup'],
  ['Cottage Cheese (low-fat)', 'dairy', 185, '1 cup'],
  ['Cottage Cheese (fat-free)', 'dairy', 120, '1 cup'],
  ['Greek Yogurt (plain, full-fat)', 'dairy', 190, '1 cup'],
  ['Greek Yogurt (plain, nonfat)', 'dairy', 130, '1 cup'],
  ['Greek Yogurt (flavored)', 'dairy', 150, '5.3 oz container'],
  ['Regular Yogurt (plain, low-fat)', 'dairy', 155, '1 cup'],
  ['Regular Yogurt (flavored)', 'dairy', 170, '6 oz container'],
  ['Skyr', 'dairy', 130, '5.3 oz container'],
  ['Kefir', 'dairy', 160, '1 cup'],
  ['Butter', 'dairy', 100, '1 tbsp'],
  ['Butter (unsalted)', 'dairy', 100, '1 tbsp'],
  ['Ghee', 'dairy', 120, '1 tbsp'],
  ['String Cheese', 'dairy', 80, '1 stick'],
  ['Cheese Curds', 'dairy', 110, '1 oz'],
  ['Mascarpone Cheese', 'dairy', 120, '2 tbsp'],
  ['Havarti Cheese', 'dairy', 105, '1 oz'],
  ['Muenster Cheese', 'dairy', 100, '1 oz'],
  ['Gruyere Cheese', 'dairy', 115, '1 oz'],
  ['Edam Cheese', 'dairy', 100, '1 oz'],
  ['Queso Fresco', 'dairy', 80, '1 oz'],
  ['Paneer', 'dairy', 85, '1 oz'],
  ['Evaporated Milk', 'dairy', 170, '1/2 cup'],
  ['Condensed Milk (sweetened)', 'dairy', 130, '2 tbsp'],
  ['Ice Cream (vanilla)', 'dairy', 270, '1 cup'],
  ['Ice Cream (chocolate)', 'dairy', 285, '1 cup'],

  // ============================================================
  // SNACK (65 items)
  // ============================================================
  ['Potato Chips (regular)', 'snack', 150, '1 oz (about 15 chips)'],
  ['Potato Chips (baked)', 'snack', 120, '1 oz'],
  ['Tortilla Chips', 'snack', 140, '1 oz (about 10 chips)'],
  ['Doritos', 'snack', 140, '1 oz (about 11 chips)'],
  ['Cheetos', 'snack', 160, '1 oz (about 21 pieces)'],
  ['Pretzels', 'snack', 110, '1 oz'],
  ['Pretzel Sticks', 'snack', 110, '1 oz'],
  ['Popcorn (air-popped)', 'snack', 30, '1 cup'],
  ['Popcorn (butter, microwave)', 'snack', 170, '3 cups popped'],
  ['Popcorn (movie theater)', 'snack', 400, '1 small bag'],
  ['Trail Mix', 'snack', 175, '1/4 cup'],
  ['Mixed Nuts (roasted, salted)', 'snack', 170, '1 oz'],
  ['Almonds', 'snack', 165, '1 oz (about 23)'],
  ['Cashews', 'snack', 155, '1 oz (about 18)'],
  ['Walnuts', 'snack', 185, '1 oz (about 14 halves)'],
  ['Pecans', 'snack', 195, '1 oz (about 19 halves)'],
  ['Pistachios', 'snack', 160, '1 oz (about 49)'],
  ['Peanuts (roasted)', 'snack', 165, '1 oz'],
  ['Macadamia Nuts', 'snack', 200, '1 oz'],
  ['Sunflower Seeds', 'snack', 165, '1 oz'],
  ['Pumpkin Seeds', 'snack', 150, '1 oz'],
  ['Chia Seeds', 'snack', 140, '1 oz'],
  ['Flax Seeds', 'snack', 150, '1 oz'],
  ['Hemp Seeds', 'snack', 170, '1 oz'],
  ['Peanut Butter', 'snack', 190, '2 tbsp'],
  ['Almond Butter', 'snack', 195, '2 tbsp'],
  ['Cashew Butter', 'snack', 190, '2 tbsp'],
  ['Sunflower Seed Butter', 'snack', 200, '2 tbsp'],
  ['Nutella', 'snack', 200, '2 tbsp'],
  ['Hummus', 'snack', 70, '2 tbsp'],
  ['Guacamole', 'snack', 50, '2 tbsp'],
  ['Salsa', 'snack', 10, '2 tbsp'],
  ['Crackers (saltine)', 'snack', 70, '5 crackers'],
  ['Crackers (wheat thins)', 'snack', 140, '16 crackers'],
  ['Crackers (Ritz)', 'snack', 80, '5 crackers'],
  ['Graham Crackers', 'snack', 130, '2 full sheets'],
  ['Rice Cakes', 'snack', 35, '1 cake'],
  ['Granola Bar', 'snack', 190, '1 bar'],
  ['Protein Bar', 'snack', 220, '1 bar'],
  ['Clif Bar', 'snack', 250, '1 bar (68g)'],
  ['Kind Bar', 'snack', 200, '1 bar'],
  ['Fig Bar', 'snack', 100, '1 bar'],
  ['Fruit Snacks', 'snack', 80, '1 pouch'],
  ['Fruit Leather', 'snack', 50, '1 strip'],
  ['Beef Stick (Slim Jim)', 'snack', 80, '1 stick'],
  ['Cheese Puffs', 'snack', 160, '1 oz'],
  ['Goldfish Crackers', 'snack', 140, '55 pieces (30g)'],
  ['Animal Crackers', 'snack', 130, '16 crackers'],
  ['Chex Mix', 'snack', 120, '2/3 cup'],
  ['Veggie Straws', 'snack', 130, '1 oz'],
  ['Dark Chocolate', 'snack', 170, '1 oz'],
  ['Milk Chocolate', 'snack', 150, '1 oz'],
  ['White Chocolate', 'snack', 160, '1 oz'],
  ['M&Ms (plain)', 'snack', 240, '1 bag (1.69 oz)'],
  ['Snickers Bar', 'snack', 250, '1 bar (1.86 oz)'],
  ['Reese\'s Peanut Butter Cup', 'snack', 210, '1 package (2 cups)'],
  ['Oreo Cookies', 'snack', 160, '3 cookies'],
  ['Chocolate Chip Cookie', 'snack', 80, '1 cookie (medium)'],
  ['Brownie', 'snack', 200, '1 square (2 in)'],
  ['Donut (glazed)', 'snack', 260, '1 donut'],
  ['Donut (chocolate frosted)', 'snack', 290, '1 donut'],
  ['Muffin (blueberry)', 'snack', 350, '1 large muffin'],
  ['Cinnamon Roll', 'snack', 310, '1 roll'],
  ['Pop-Tart', 'snack', 200, '1 pastry'],
  ['Rice Krispie Treat', 'snack', 90, '1 bar'],

  // ============================================================
  // BEVERAGE (55 items)
  // ============================================================
  ['Black Coffee', 'beverage', 2, '8 oz'],
  ['Coffee with Cream', 'beverage', 50, '8 oz'],
  ['Coffee with Cream and Sugar', 'beverage', 80, '8 oz'],
  ['Espresso', 'beverage', 5, '1 shot'],
  ['Latte (whole milk)', 'beverage', 190, '12 oz'],
  ['Latte (skim milk)', 'beverage', 120, '12 oz'],
  ['Cappuccino', 'beverage', 120, '12 oz'],
  ['Mocha', 'beverage', 290, '12 oz'],
  ['Iced Coffee (sweetened)', 'beverage', 120, '12 oz'],
  ['Iced Coffee (unsweetened)', 'beverage', 5, '12 oz'],
  ['Cold Brew Coffee', 'beverage', 5, '12 oz'],
  ['Frappuccino (caramel)', 'beverage', 380, '16 oz'],
  ['Black Tea', 'beverage', 2, '8 oz'],
  ['Green Tea', 'beverage', 2, '8 oz'],
  ['Sweet Tea', 'beverage', 90, '8 oz'],
  ['Chai Tea Latte', 'beverage', 200, '12 oz'],
  ['Matcha Latte', 'beverage', 175, '12 oz'],
  ['Herbal Tea', 'beverage', 0, '8 oz'],
  ['Coca-Cola', 'beverage', 140, '12 oz can'],
  ['Diet Coke', 'beverage', 0, '12 oz can'],
  ['Pepsi', 'beverage', 150, '12 oz can'],
  ['Dr Pepper', 'beverage', 150, '12 oz can'],
  ['Sprite', 'beverage', 140, '12 oz can'],
  ['Mountain Dew', 'beverage', 170, '12 oz can'],
  ['Ginger Ale', 'beverage', 130, '12 oz can'],
  ['Root Beer', 'beverage', 165, '12 oz can'],
  ['Club Soda', 'beverage', 0, '12 oz'],
  ['Tonic Water', 'beverage', 125, '12 oz'],
  ['Sparkling Water (flavored)', 'beverage', 0, '12 oz'],
  ['Orange Juice', 'beverage', 110, '8 oz'],
  ['Apple Juice', 'beverage', 115, '8 oz'],
  ['Cranberry Juice Cocktail', 'beverage', 140, '8 oz'],
  ['Grape Juice', 'beverage', 150, '8 oz'],
  ['Grapefruit Juice', 'beverage', 95, '8 oz'],
  ['Tomato Juice', 'beverage', 40, '8 oz'],
  ['V8 Vegetable Juice', 'beverage', 50, '8 oz'],
  ['Lemonade', 'beverage', 100, '8 oz'],
  ['Limeade', 'beverage', 100, '8 oz'],
  ['Fruit Punch', 'beverage', 110, '8 oz'],
  ['Coconut Water', 'beverage', 45, '8 oz'],
  ['Almond Milk (unsweetened)', 'beverage', 30, '1 cup'],
  ['Almond Milk (sweetened)', 'beverage', 60, '1 cup'],
  ['Oat Milk', 'beverage', 120, '1 cup'],
  ['Soy Milk (unsweetened)', 'beverage', 80, '1 cup'],
  ['Soy Milk (sweetened)', 'beverage', 110, '1 cup'],
  ['Rice Milk', 'beverage', 115, '1 cup'],
  ['Sports Drink (Gatorade)', 'beverage', 140, '20 oz bottle'],
  ['Energy Drink (Red Bull)', 'beverage', 110, '8.4 oz can'],
  ['Energy Drink (Monster)', 'beverage', 210, '16 oz can'],
  ['Kombucha', 'beverage', 50, '8 oz'],
  ['Protein Shake (chocolate)', 'beverage', 160, '11 oz bottle'],
  ['Smoothie (fruit)', 'beverage', 250, '16 oz'],
  ['Hot Chocolate', 'beverage', 190, '8 oz'],
  ['Apple Cider', 'beverage', 120, '8 oz'],
  ['Eggnog', 'beverage', 340, '1 cup'],

  // ============================================================
  // CONDIMENT (55 items)
  // ============================================================
  ['Ketchup', 'condiment', 20, '1 tbsp'],
  ['Mustard (yellow)', 'condiment', 3, '1 tsp'],
  ['Mustard (dijon)', 'condiment', 5, '1 tsp'],
  ['Mustard (honey)', 'condiment', 10, '1 tsp'],
  ['Mustard (whole grain)', 'condiment', 5, '1 tsp'],
  ['Mayonnaise', 'condiment', 95, '1 tbsp'],
  ['Mayonnaise (light)', 'condiment', 35, '1 tbsp'],
  ['Ranch Dressing', 'condiment', 75, '1 tbsp'],
  ['Ranch Dressing (light)', 'condiment', 40, '1 tbsp'],
  ['Italian Dressing', 'condiment', 45, '1 tbsp'],
  ['Caesar Dressing', 'condiment', 80, '1 tbsp'],
  ['Blue Cheese Dressing', 'condiment', 75, '1 tbsp'],
  ['Thousand Island Dressing', 'condiment', 60, '1 tbsp'],
  ['Balsamic Vinaigrette', 'condiment', 45, '1 tbsp'],
  ['Honey Mustard Dressing', 'condiment', 60, '1 tbsp'],
  ['French Dressing', 'condiment', 70, '1 tbsp'],
  ['Olive Oil', 'condiment', 120, '1 tbsp'],
  ['Vegetable Oil', 'condiment', 120, '1 tbsp'],
  ['Coconut Oil', 'condiment', 120, '1 tbsp'],
  ['Sesame Oil', 'condiment', 120, '1 tbsp'],
  ['Soy Sauce', 'condiment', 10, '1 tbsp'],
  ['Soy Sauce (low sodium)', 'condiment', 10, '1 tbsp'],
  ['Teriyaki Sauce', 'condiment', 15, '1 tbsp'],
  ['Hot Sauce', 'condiment', 0, '1 tsp'],
  ['Sriracha', 'condiment', 5, '1 tsp'],
  ['Tabasco', 'condiment', 0, '1 tsp'],
  ['BBQ Sauce', 'condiment', 30, '1 tbsp'],
  ['Worcestershire Sauce', 'condiment', 5, '1 tsp'],
  ['Steak Sauce (A1)', 'condiment', 15, '1 tbsp'],
  ['Hoisin Sauce', 'condiment', 35, '1 tbsp'],
  ['Fish Sauce', 'condiment', 5, '1 tsp'],
  ['Oyster Sauce', 'condiment', 10, '1 tbsp'],
  ['Salsa Verde', 'condiment', 10, '2 tbsp'],
  ['Pico de Gallo', 'condiment', 5, '2 tbsp'],
  ['Tzatziki', 'condiment', 25, '2 tbsp'],
  ['Chimichurri', 'condiment', 60, '2 tbsp'],
  ['Pesto', 'condiment', 80, '2 tbsp'],
  ['Marinara Sauce', 'condiment', 35, '1/4 cup'],
  ['Alfredo Sauce', 'condiment', 90, '1/4 cup'],
  ['Tartar Sauce', 'condiment', 70, '1 tbsp'],
  ['Cocktail Sauce', 'condiment', 30, '2 tbsp'],
  ['Honey', 'condiment', 65, '1 tbsp'],
  ['Maple Syrup', 'condiment', 50, '1 tbsp'],
  ['Pancake Syrup', 'condiment', 55, '1 tbsp'],
  ['Jam/Jelly', 'condiment', 50, '1 tbsp'],
  ['Marmalade', 'condiment', 50, '1 tbsp'],
  ['Relish (sweet pickle)', 'condiment', 20, '1 tbsp'],
  ['Pickle (dill)', 'condiment', 5, '1 spear'],
  ['Olives (black)', 'condiment', 25, '5 olives'],
  ['Olives (green)', 'condiment', 20, '5 olives'],
  ['Capers', 'condiment', 2, '1 tbsp'],
  ['Apple Cider Vinegar', 'condiment', 0, '1 tbsp'],
  ['Balsamic Vinegar', 'condiment', 15, '1 tbsp'],
  ['Red Wine Vinegar', 'condiment', 0, '1 tbsp'],
  ['Tahini', 'condiment', 90, '1 tbsp'],
];

async function seed() {
  const client = await pool.connect();

  try {
    console.log(`Seeding ${foods.length} foods into food_database...`);

    // Build parameterized query
    const values = [];
    const params = [];
    let paramIndex = 1;

    for (const [name, category, calories, servingSize] of foods) {
      values.push(`($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3})`);
      params.push(name, category, calories, servingSize);
      paramIndex += 4;
    }

    const query = `
      INSERT INTO food_database (name, category, calories_per_serving, serving_size)
      VALUES ${values.join(',\n             ')}
      ON CONFLICT DO NOTHING;
    `;

    const result = await client.query(query, params);
    console.log(`Successfully inserted ${result.rowCount} foods into food_database.`);
  } catch (err) {
    console.error('Error seeding foods:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
    process.exit(0);
  }
}

seed();
